export const CATEGORIES_GET_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_GET_SUCCESS = "CATEGORIES_GET_SUCCESS";
export const CATEGORIES_GET_FAILURE = "CATEGORIES_GET_FAILURE";
export const CATEGORY_FOR_JOKE = "CATEGORY_FOR_JOKE";

export const RANDOM_JOKE_REQUEST = "RANDOM_JOKE_REQUEST";
export const RANDOM_CATEGORY_JOKE_REQUEST = "RANDOM_CATEGORY_JOKE_REQUEST";
export const RANDOM_JOKE_SUCCESS = "RANDOM_JOKE_SUCCESS";
export const RANDOM_JOKE_FAILURE = "RANDOM_JOKE_FAILURE";

export const SEARCH_JOKES_REQUEST = "SEARCH_JOKES_REQUEST";
export const SEARCH_JOKES_SUCCESS = "SEARCH_JOKES_SUCCESS";
export const SEARCH_JOKES_FAILURE = "SEARCH_JOKES_FAILURE";
export const SEARCH_JOKES_QUERY = "SEARCH_JOKES_QUERY";

export const FAVORITE_JOKES_GET = "FAVORITE_JOKES_GET";
export const FAVORITE_JOKE_ADD_INIT = "FAVORITE_JOKE_ADD_INIT";
export const FAVORITE_JOKE_ADD_REQUEST = "FAVORITE_JOKE_ADD_REQUEST";
export const FAVORITE_JOKE_ADD_SUCCESS = "FAVORITE_JOKE_ADD_SUCCESS";
export const FAVORITE_JOKE_REMOVE_INIT = "FAVORITE_JOKE_REMOVE_INIT";
export const FAVORITE_JOKE_REMOVE_REQUEST = "FAVORITE_JOKE_REMOVE_REQUEST";
export const FAVORITE_JOKE_REMOVE_SUCCESS = "FAVORITE_JOKE_REMOVE_SUCCESS";

